num_records: 100
output_dir: yaml_test
seed: 123
output_format: csv
age_dist:
  0-18: 0.1
  19-40: 0.2
  41-65: 0.4
  66-120: 0.3
gender_dist:
  male: 0.7
  female: 0.3
race_dist:
  White: 0.5
  Black: 0.2
  Asian: 0.1
  Hispanic: 0.1
  Other: 0.1
smoking_dist:
  Never: 0.6
  Former: 0.2
  Current: 0.2
alcohol_dist:
  Never: 0.4
  Occasional: 0.3
  Regular: 0.2
  Heavy: 0.1
education_dist:
  High School: 0.2
  Bachelor: 0.3
  Master: 0.2
  Doctorate: 0.1
  None: 0.2
employment_dist:
  Employed: 0.5
  Unemployed: 0.1
  Student: 0.2
  Retired: 0.1
  Disabled: 0.1
housing_dist:
  Stable: 0.8
  Homeless: 0.05
  Temporary: 0.1
  Assisted Living: 0.05

